### ISSUE TITLE
Error of use dump::* methods at the end file (without empty line of close tag)

### ISSUE THREAD

**Issue by cmirnow** [Hubbitus/HuPHP#1]
Hi, this code 

<?
$file = simplexml_load_file("http://www.cbr.ru/scripts/XML_daily.asp?date_req=".date("d/m/Y"));
include('../../../HuPHP/autoload.php');
dump::a($xml);

initializes this collision. May be, it is a reaction to the exchange rate of Russian rouble? :))

Notice: Undefined variable: xml in /home/c/cl261629/public_html/mstp_mod/geo/del.php on line 4

Fatal error: Uncaught exception 'VariableRangeException' with message 'Overflow! This offset does not exists.' in /home/c/cl261629/HuPHP/Filesystem/file_inmem.php:195 Stack trace: #0 /home/c/cl261629/HuPHP/Debug/Tokenizer.php(194): file_inmem->getLineByOffset(143) #1 /home/c/cl261629/HuPHP/Debug/Tokenizer.php(220): Tokenizer->findCallStrings() #2 /home/c/cl261629/HuPHP/Debug/Tokenizer.php(238): Tokenizer->parseTokens() #3 /home/c/cl261629/HuPHP/Debug/debug.php(105): Tokenizer->parseCallArgs() #4 /home/c/cl261629/HuPHP/Debug/debug.php(210): dump::getHeader(false, NULL) #5 /home/c/cl261629/HuPHP/Debug/debug.php(258): dump::w(NULL, false, false) #6 /home/c/cl261629/HuPHP/Debug/debug.php(267): dump::auto(NULL, false, false) #7 /home/c/cl261629/public_html/mstp_mod/geo/del.php(4): dump::a(NULL) #8 {main} thrown in /home/c/cl261629/HuPHP/Filesystem/file_inmem.php on line 195

**Comment by Hubbitus** [comment]
It is possibly reaction to end of file without close php tag. Thank you very much for the bugreport. I'll try fix it shortly.
